name = "minis"
license = "MIT"
licenselink = "https://github.com/lowejan/hugo-minis/blob/master/LICENSE.md"
description = "Minimal and Simple Hugo theme."
homepage = "https://minis.lujok.com/"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "WeJan"
  homepage = "https://lujok.com"
